### ISSUE TITLE
Is there a corresponding paper for this code?

### ISSUE THREAD

**Issue by zhangchenlu999** [da-da-chen/MOMPA#1]
Is there a corresponding paper for this code?

**Comment by da-da-chen** [comment]
Yes, the relevant articles are as follows.
【1】Chen L, Cai X, Jin K, et al. MOMPA: A high performance multi-objective optimizer based on marine predator algorithm[C]//Proceedings of the Genetic and Evolutionary Computation Conference Companion. 2021: 177-178.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "da-da-chen/MOMPA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 中午11:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[da-da-chen/MOMPA] Is there a corresponding paper for this code? (Issue #1)





 
Is there a corresponding paper for this code?

**Comment by zhangchenlu999** [comment]
Thank you for your reply！
